FROM python:3.12.10-slim-bookworm

RUN pip install --no-cache-dir \
    "mlflow[auth]==3.16.0" \
    "psycopg2-binary==2.9.10" \
    "boto3==1.37.34"

COPY docker/mlflow-entrypoint.sh /usr/local/bin/mlflow-entrypoint
COPY docker/mlflow-healthcheck.py /usr/local/bin/mlflow-healthcheck

RUN chmod 755 /usr/local/bin/mlflow-entrypoint /usr/local/bin/mlflow-healthcheck

ENTRYPOINT ["/usr/local/bin/mlflow-entrypoint"]
